name: nutri_teca
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.1
  get_it: ^7.6.7
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^26.2.7 
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  animated_custom_dropdown: ^3.1.1
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4
  provider: ^6.1.2
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.6
  image: ^4.3.0
  google_mobile_ads: ^5.2.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  dartz: ^0.10.1
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.9

  retrofit_generator: ^8.2.1

flutter:
  generate: true
  
  uses-material-design: true
  assets: 
    - assets/logos/
    - assets/icons/
  
  fonts: 
    - family: DancingScript
      fonts: 
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 900
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
