name: food_macros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.2.0
  dio: ^5.5.0
  retrofit: ">=4.1.0"
  flutter_bloc: ^8.1.6
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets: 
    - assets/logos/
  
  fonts: 
    - family: DancingScript
      fonts: 
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 900
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
